### ISSUE TITLE
Allow Go library to act as an SCP sink

### ISSUE THREAD

**Issue by bramvdbogaerde** [bramvdbogaerde/go-scp#1]
Currently only local files can be copied over that a remote location. 
If the library allows to act as an SCP sink files could be copied to other way around enabling the possibility to download files.

Proposal for this new interface:

```
func (c *Client) CopyFromRemote(remote_path string, writer: io.Writer)
```

The only problem here is that an SCP source can send the permissions of the file, in this proposal  no way to enforce permissions is provided because of the use of the general io.Writer. This allows us however to make no assumptions about the destination of the file.

Therefore a second proposal can be proposed:

```
func (c *Client) CopyFromRemote(remote_path: string, writer: io.Writer) (permission int)
```

Here the user of the `CopyFromRemote` function can use the return value to determine which permissions are intended by the server and integrate them in whatever the io.Writer is writing to.

**Comment by heicat** [comment]
I just have a way to enable this function, use 'dd if=input' method, i start a pr.

**Comment by DDandKD** [comment]
I'd love to see this sink merged in as well.  Thanks a ton for contributing this package.

**Comment by bramvdbogaerde** [comment]
At last! Included in the library as `CopyFromRemote`.
