### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by bencaron** [bramvdbogaerde/go-scp#10]
Your library looks really nice, clean and simple to use, but there is no LICENSE file in the project, so technically nobody can really use it as it is explained here: https://choosealicense.com/no-permission/

Could you consider adding a license please? Github also have a documentation section to help you choose the one that fit your intention: https://help.github.com/articles/licensing-a-repository/

Thanks!

**Comment by bramvdbogaerde** [comment]
I didn't realy notice it until now. Indeed this project does not have a license attached to it.
Thanks for notifying me about it, I will fix it tomorrow.

**Comment by bramvdbogaerde** [comment]
I am sorry for the delay, I added a license now.

The license makes it possible to use the library in any larger work without disclosing the source of the larger work, only any modification of the covered work (this library) is necassary.

I hope this works for you.

**Comment by bramvdbogaerde** [comment]
I will close this issue now @bencaron.

If you have any questions about the project, don't hesitate to contact me or to open an issue.
