### ISSUE TITLE
Default remote-binary should be 'scp'

### ISSUE THREAD

**Issue by siggimoo** [bramvdbogaerde/go-scp#17]
The default remote-binary (currently `/usr/bin/scp`) should probably just be `scp`. It allows the remote-end to be responsible for the path to its own executable. It's also what OpenSSH does:

```
/* Command to be executed on remote system using "ssh". */
	(void) snprintf(cmd, sizeof cmd, "scp%s%s%s%s",
	    verbose_mode ? " -v" : "",
	    iamrecursive ? " -r" : "", pflag ? " -p" : "",
	    targetshouldbedirectory ? " -d" : "");
```

**Comment by bramvdbogaerde** [comment]
Seems sensible to me, this should be fixed with the last commit.

I still believe the configuration option can be useful, for any exotic use cases, for example when the scp binary is not on the PATH.
