### ISSUE TITLE
Add more operations

### ISSUE THREAD

**Issue by rogierlommers** [bramvdbogaerde/go-scp#18]
Hey! Thanks for your package! I have a question though: are you open for more implementations of the protocol? For example: listing files, deleting files, etc.

**Comment by bramvdbogaerde** [comment]
I think that the operations you suggest can be useful to many, and some of them are quite trivial to implement.

However, I'm unsure whetever the implementation of these operations are in the scope of this project, as the original purpose of this project was to provide a SCP client for the Go language, as opposed to a full remote file transfer protocol (ie. sftp).

These things considered, I think these operations can be valuable. I will see how the operations can fit in the library in the next few days, and I will keep you posted with my findings.

**Comment by rogierlommers** [comment]
Yeah, basically it's not secure copy anymore, but a full sftp client :).

**Comment by DrunkenPoney** [comment]
Is there a way to copy a file from the remote server to the local computer?
If there is a way to do so then how?

**Comment by bramvdbogaerde** [comment]
I have decided that additional operations such as listing and deleting files are outside of the scope of this project, as they are not strictly included in SCP itself, and would require a large overhaul of the project.
