### ISSUE TITLE
ssh: handshake failed: ssh: no common algorithm for key exchange; client offered: [curve25519-sha256@libssh.org ecdh-sha2-nistp256 ecdh-sha2-nistp384 ecdh-sha2-nistp521 diffie-hellman-group14-sha1 diffie-hellman-group1-sha1], server offered: [diffie-hellman-group-exchange-sha256]

### ISSUE THREAD

**Issue by ranjitkumar2k10** [bramvdbogaerde/go-scp#21]
Hi,

Thanks for this module.. when i am testing i am facing this issue,.
i changed the PrivateKey function in auth/key.go
                User: username,
                Auth: []ssh.AuthMethod{
                        ssh.PublicKeys(signer),
                },
                **Config: ssh.Config{
                KeyExchanges: []string{"diffie-hellman-group-exchange-sha256"},
                },**
                HostKeyCallback: keyCallBack,
        }, nil

it will work only for latest go binaries .

**Comment by bramvdbogaerde** [comment]
First, thanks for your interest in the library. 

Indeed, Go has only recently added an implementation for the DH-group-exchange-sha256 (June 3 [1]). 

However, it does seem that it is not enabled by default as a key exchange algorithm on both server and client (as indicated in [2] by the abscence of kexAlgoDHGEXSHA256).

If I understand your issue correctly, you seem to have a problem with a server that only offers the `diffie-hellman-group-exchange-sha256`  algorithm, and suggest that we change the function in `auth/key.go` to one that includes a configuration for **only** accepting the `diffie-hellman-group-exchange-sha256`. Is that correct?

If so, I would advice against that as it severely limits the amount of servers the scp client could communicate with. 

I would love to hear your suggestions.

[1] https://github.com/golang/crypto/commit/57b3e21c3d5606066a87e63cfe07ec6b9f0db000
[2] https://github.com/golang/crypto/blob/57b3e21c3d5606066a87e63cfe07ec6b9f0db000/ssh/common.go#L46

As a sidenote, Github supports markdown for formatting issues. Using markdown you can make some parts of your issue display as a code block, like so:

```
{
   User: username,
   Auth: []ssh.AuthMethod{
   ssh.PublicKeys(signer),
},
Config: ssh.Config{
   KeyExchanges: []string{"diffie-hellman-group-exchange-sha256"},
},
   HostKeyCallback: keyCallBack,
}, nil
```

reference: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code

**Comment by ranjitkumar2k10** [comment]
Hi,
your comment is very much valid!!! i just hinted that this kexAlgoDHGEXSHA256 algo support.

Anyway your arealy having more information on this..

Thanks for your suggestion on README, will take care in future.

**Comment by bramvdbogaerde** [comment]
Alright then, I note that you suggest to add the _kexAlgoDHGEXSHA256 _ to the list of default key exchange algorithms for both the private- and password authentication methods.

I will update this issue once I decided what changes to make exactly.

Thanks for suggestion.

**Comment by bramvdbogaerde** [comment]
I will close this issue as the user could set the key algorithms manually using `ClientConfigurer.ClientConfig` and add the algorithm when neccessary.
