### ISSUE TITLE
Wrong file name on remote host

### ISSUE THREAD

**Issue by lexfrei** [bramvdbogaerde/go-scp#22]
Hi!

I can't create subdirs with your tool. And it's not clear for me why this is not handled. Looks like we need an error in this case.
So, I'm trying to do something like `c.CopyFile(f, /existing/new/filename.tgz, "0655")` and i got /existing/new as result file. File just copied fine, but it got the wrong name and subdir is missing

<details>

    c := scp.NewClient(s.host, &cfg)

	err = c.Connect()
	if err != nil {
		return fmt.Errorf("can't connect to remote host: %s", err)
	}
	defer c.Close()

	f, err := os.Open(file)
	if err != nil {
		return fmt.Errorf("can't open file: %s", err)
	}
	defer f.Close()

	err = c.CopyFile(f, path.Join(s.path, filepath.Base(file)), "0655")

	if err != nil {
		return fmt.Errorf("can't copy file: %s", err)
	}
</details>

**Comment by bramvdbogaerde** [comment]
As I mentioned on Twitter, I will investigate this issue tomorrow (UTC+3).

**Comment by lexfrei** [comment]
Some extra info:

I'm testing this with localhost, my versions:
<details>


```
lex@192-168-11-231:~/git/puppet$ ssh -V
OpenSSH_7.9p1, LibreSSL 2.7.3
✓ @ Fri Aug 30 12:41:28 MSK 2019
lex@192-168-11-231:~/git/puppet$ scp --version
rsync  version 3.1.3  protocol version 31
Copyright (C) 1996-2018 by Andrew Tridgell, Wayne Davison, and others.
Web site: http://rsync.samba.org/
Capabilities:
    64-bit files, 64-bit inums, 64-bit timestamps, 64-bit long ints,
    socketpairs, hardlinks, symlinks, IPv6, batchfiles, inplace,
    append, ACLs, xattrs, iconv, symtimes, no prealloc, file-flags

rsync comes with ABSOLUTELY NO WARRANTY.  This is free software, and you
are welcome to redistribute it under certain conditions.  See the GNU
General Public Licence for details.
✓ @ Fri Aug 30 12:41:30 MSK 2019
lex@192-168-11-231:~/git/puppet$ go version
go version go1.12.9 darwin/amd64
✓ @ Fri Aug 30 12:41:33 MSK 2019

```

**Comment by bramvdbogaerde** [comment]
Thank you for the extra details.

**Comment by lexfrei** [comment]
scp fails if I'm trying to copy to the nonexisting path (also with -r):
```
lex@192-168-11-231:~$ \scp -r ./bigfile localhost:~/Desktop/lul/bigfile
scp: /Users/lex/Desktop/lul/bigfile: No such file or directory
✗: 1 @ Fri Aug 30 14:03:46 MSK 2019
lex@192-168-11-231:~$ \scp ./bigfile localhost:~/Desktop/lul/bigfile
scp: /Users/lex/Desktop/lul/bigfile: No such file or directory
✗: 1 @ Fri Aug 30 14:04:25 MSK 2019
```
So, we need to add some checks for this.
Not sure, how to do this correctly: do we need to fail as the scp does. Or, create the path with extra `mkdir -p ${path}` other ssh

**Comment by bramvdbogaerde** [comment]
I am not really in favour of automatically creating non existing paths, maybe we can provide it as an extra options but I wouldn't enable it by default.

As for the actual errors, they should have been solved in a previous pull request, however it is possible that not all possibilities are covered in that code, I will take a look at it shortly.

Thanks for your helpful additional information.

**Comment by bramvdbogaerde** [comment]
@lexfrei Commit 50cfc22f160ef330453db02ad70b5c90fb718c56 introduces more checks and better error reporting when receiving responses from the remote that a transfer has failed.

**Comment by bramvdbogaerde** [comment]
As a follow up, the library now reports failure when trying to copy to a non existing path. 

Eg. 
```
	// Connect to the remote server
	err := client.Connect()
	if err != nil {
		fmt.Println("Couldn't establisch a connection to the remote server ", err)
		return
	}

	// Open a file
	f, _ := os.Open("./test.txt")

	// Close client connection after the file has been copied
	defer client.Close()

	// Close the file after it has been copied
	defer f.Close()

	// Finaly, copy the file over
	// Usage: CopyFile(fileReader, remotePath, permission)

	err = client.CopyFile(f, "/home/server/non/existing/path/test.txt", "0655")

	if err != nil {
		fmt.Println("Error while copying file ", err)
	}
```

reports `Error while copying file  scp: /home/server/non/existing/path: No such file or directory`.

I have checked your example and it still exhibits strange behaviour, so it seems that the problem persists if you just have one level of non-existing directories (eg. /new/file as opposed to /new1/new2/file).
