### ISSUE TITLE
Information about the progress of the transfer

### ISSUE THREAD

**Issue by yllan** [bramvdbogaerde/go-scp#23]
Is it possible to get the transferring rate/ETA/progress?

**Comment by bramvdbogaerde** [comment]
At the moment this is not possible, as the SCP protocol itself does not give us any feedback about the progress on the remote, and we use a simple `io.Copy` for transferring the file itself.

However we can adopt something like `io.TeeReader` to keep count of how many bytes have been transferred up to a certain point, and use that for calculating numbers such as the transfer reta, estimated time of arrival and the overall progress.

I think your proposal is could be an interesting feature worth including. I will keep this issue open for tracking its progress.

**Comment by bramvdbogaerde** [comment]
Pull request #29 seems to provide a promising way of keeping track of the information you are describing, it is in the progress of being merged.

**Comment by bramvdbogaerde** [comment]
I consider this solved per pull request #29. 
Please let me know if those changes do not cover your desired use case.
