### ISSUE TITLE
Is it possible to copy from a remote path?

### ISSUE THREAD

**Issue by atye** [bramvdbogaerde/go-scp#27]
I may be missing this in the godoc, but it seems like we can only copy a file from local to remote. Is there functionality to copy a file from remote to local?

**Comment by atye** [comment]
I see [https://github.com/bramvdbogaerde/go-scp/pull/12](url) is opened for this but there hasn't been much activity on it lately.

**Comment by bramvdbogaerde** [comment]
First of all, thanks for your interest in my library and you are entirely right. 
This feature has been on the roadmap for quite some time, see #1.

Pull request #12 indeed addresses this issue, unfortunately it is now a little bit out of sync with the current code base, so some small changes would be required to integrate it properly.

I don't have much free time on my hands at the moment, but I will try to take a look at the proposed changes as soon as possible.
