### ISSUE TITLE
downloadFile

### ISSUE THREAD

**Issue by UrbanskiDawid** [bramvdbogaerde/go-scp#31]
am I missing something? how can I download a file?

**Comment by bramvdbogaerde** [comment]
Thanks for your interest in the library.

The library does not support SCP sink mode yet, which means that it currently can only upload files.
This is a very frequently requested feature and several pull requests have been opened which
propose a solution for this feature, I hope to incorporate those ideas in the near future.

I will close this issue as it has been requested and proposed in issue #1, pull request #30 and pull request #12.
