### ISSUE TITLE
Multiple consecutive `CopyFile` calls produce `ssh: StdoutPipe after process started` error

### ISSUE THREAD

**Issue by brumhard** [bramvdbogaerde/go-scp#50]
Hi there,

I stumbled upon a bug in the implementation of `CopyFile`.
It works just fine when copying a single file with the client. As soon as you try to copy the second file an error will occur with the following message: `ssh: StdoutPipe after process started`.

You can reproduce that by changing your test function `TestCopy` and adding another `CopyFile` call to it like:

```Go
func TestCopy(t *testing.T) {
	client := establishConnection(t)
	defer client.Close()

	// Open a file we can transfer to the remote container.
	f, _ := os.Open("./data/upload_file.txt")
	defer f.Close()

	// Create a file name with exotic characters and spaces in them.
	// If this test works for this, simpler files should not be a problem.
	filename := "Exöt1ç uploaded file.txt"

	// Finaly, copy the file over.
	// Usage: CopyFile(fileReader, remotePath, permission).
	err := client.CopyFile(f, "/data/"+filename, "0777")
	if err != nil {
		t.Errorf("Error while copying file: %s", err)
	}

	// copy the second file
	err = client.CopyFile(f, "/data/"+filename, "0777")
	if err != nil {
		t.Errorf("Error while copying file 2: %s", err)
	}

	// Read what the receiver have written to disk.
	content, err := ioutil.ReadFile("./tmp/" + filename)
	if err != nil {
		t.Errorf("Result file could not be read: %s", err)
	}

	text := string(content)
	expected := "It Works\n"
	if strings.Compare(text, expected) != 0 {
		t.Errorf("Got different text than expected, expected %q got, %q", expected, text)
	}
}
```

This will lead to the test failing.

Looking at the code I think the problem is that the `ssh.Session` is reused across the whole client lifetime. Actually, I think one session should only be used for a single command. So I guess the bug could be fixed by creating a new session for each copy call.

If you accept PRs I can also try to help here.

**Comment by bramvdbogaerde** [comment]
Interesting. 

I definitely accept PRs, so feel free to make a proposal.

**Comment by marco-m** [comment]
> Looking at the code I think the problem is that the ssh.Session is reused across the whole client lifetime. Actually, I think one session should only be used for a single command. So I guess the bug could be fixed by creating a new session for each copy call.

I think this is correct.

Note also that CopyFromRemote, when the client has already been used for one CopyFromFile, will have an even worse behavior: it will just hang.

**Comment by brumhard** [comment]
Hi there @bramvdbogaerde, sry haven't got the time to investigate further and open a PR. Instead I moved to https://github.com/pkg/sftp which looks like the better solution for my usecase.
Hope you can still work on it with the hints by me and @marco-m.

**Comment by bramvdbogaerde** [comment]
`CopyFromRemote` and `CopyFromFile` are two completely different SCP modes, so they are incompatible. Regardless, the library should probably return an error in case SCP is started is source mode. 

With regards to the issue with `CopyFromFile` followed by another `CopyFromFile: I believe that the same SSH session can be re-used for consecutive calls, this is after all what "scp -r" does.

**Comment by santoshkowshikhr** [comment]
I ran into the same issue today, single file copy works fine, when I try to send more than one file it gives the same error.

> Error while copying file  ssh: StdoutPipe after process started


```
	dirCnt, err2 := ioutil.ReadDir("./builds")
	if err2 != nil {
		log.Fatal(err2)
	}

            for _, val := range dirCnt {
		err1 := client.Connect()
		if err1 != nil {
			fmt.Println("Couldn't establish a connection to the remote server ", err)
			return err1
		}

		if val.Name() == "go-file" || val.Name() == "version.txt" {

			fmt.Printf("%v/%v", "builds", val.Name())
			filename := fmt.Sprintf("%v/%v", "builds", val.Name())
			file, err := os.Open(filename)
			if err != nil {
				log.Fatal(err)
			}

			defer client.Close()
			defer file.Close()

			destFile := fmt.Sprintf("%v/%v", "/data", val.Name())
			err1 := client.CopyFromFile(context.Background(), *file, destFile, "0755")
			if err1 != nil {
				fmt.Println("Error while copying file ", err1)
			}
		}
	}
```
let me know if there is any workaround for this. Thank you 👍

**Comment by aalexisp** [comment]
Hello, 

I am writing to know if there has been any updated in this as I am currently working with this package in my final thesis and I am a bit blocked as I need to download multiple files from a remote server.

Thank you!

**Comment by bramvdbogaerde** [comment]
I am looking for a solution, for now you will have to recreate a client, and download/upload the other files like that. The current implementation is only for copying a **single file**.

If you are asking for a recursive copy: that is not yet implemented, but would be a nice addition to the library (it has to do with the "-r" option, and we will need support for a few more control messages).

I don't have much time myself to do debugging and/or coding for now, so any contributions are welcome!

I will close this issue, in favor of opening three separate issues, so that new contributors can find what can be worked on: #59 , #60 and #61.
