### ISSUE TITLE
I'm sorry to mention this issue

### ISSUE THREAD

**Issue by T-TRz879** [bramvdbogaerde/go-scp#69]
I want to know why there are ack and checkResponse operations when getting and uploading files. It is based on tcp. Does it need to conform to the three handshake specification.
I'm sorry to bother you @bramvdb

**Comment by bramvdbogaerde** [comment]
Indeed, you are correct that SCP runs over an SSH session which in turn usually runs over TCP.  However, I think you are confusing transport layer (TCP) with application layer here (SCP). 

The checkReponse operations check whether the remote has rejected our commands for some reason (e.g., invalid path, insufficient free disk space, malformed request, ...). These things are not expressed by TCP, which simply assures that our commands will eventually arrive in the correct order at the remote. This is similar to HTTP/1 which also features status codes while it runs over TCP. Another example of this is SMTP which responds with an 'OK'  or 'ERROR' message after each command. 

I hope this clears up some of the confusion.

**Comment by T-TRz879** [comment]
@bramvdbogaerde Oh Thank you!! There are reference materials about the underlying operation of scp or smtp, so that I can know how to communicate between their clients and servers, and some rules

**Comment by bramvdbogaerde** [comment]
Yes, there are plenty of materials available. I cannot comment on the best reference material for SMTP (although RFC2821 might be a good start), but for this library, the following source was primarily used: https://web.archive.org/web/20090806212235/http://blogs.sun.com/janp/entry/how_the_scp_protocol_works. 

With regards to your original question about acknowledgements, I think this line in the post summarizes this quite well:
> The scp in source mode (= data producer) always waits for a reply before the next protocol line is sent.

**Comment by bramvdbogaerde** [comment]
Thank your for your interest in this library and the SCP protocol in general. But since Github issues is not a discussion forum, I will lock this conversation.
