### ISSUE TITLE
Create directory if target path does not exist on remote host

### ISSUE THREAD

**Issue by jantytgat** [bramvdbogaerde/go-scp#78]
Hi,

I'd like to know if go-scp supports the creation of directories on the remote host if the target does not exist.
If not, how can I help to add this?

Kind regards,
Jan

**Comment by jantytgat** [comment]
In the meantime, I've done some research, and it means sending a separate command over the SSH connection to create the directory (mkdir -p).

Would it be a change in public API if such a function were added to your SCP client?
Given that the SSH client is not publicly accessible outside your package, I would need to set up the SSH connection externally and call NewClientBySSH to make this possible.

It would be nice to provide the functionality straight from your package.

**Comment by bramvdbogaerde** [comment]
Creating directories automatically would be nice but I think it falls outside the scope of this package. Perhaps you want to look into go-sftp which provides this functionality as part of the SFTP protocol.
