### ISSUE TITLE
ssh session keeps open on sshd

### ISSUE THREAD

**Issue by cedricve** [bramvdbogaerde/go-scp#8]
I tried your library and it works great, however it keeps existing connections open..

![screen shot 2018-07-05 at 16 40 20](https://user-images.githubusercontent.com/1546779/42329892-20974198-8072-11e8-8609-7e6208f556e6.png)

**Comment by bramvdbogaerde** [comment]
That is not very desirable indeed.
I will take a look at it one of the following days.

Thansk for reporting.

**Comment by bramvdbogaerde** [comment]
It cannot reproduce your problem.
Can you maybe give some example code in which this problem occurs?

Thanks.

**Comment by cedricve** [comment]
Sure.. What I'm doing is starting the SCP on a GET request.

	proxy.OnRequest().DoFunc(func(r *http.Request, ctx *goproxy.ProxyCtx) (*http.Request, *http.Response) {

		// Read image or video from request.
		body, err := ioutil.ReadAll(r.Body)
		if err != nil {
		    log.Printf("Error reading body: %v", err)
		}

		// Get key from Request.
		fmt.Printf("Request: %s %s\n", r.Host, r.URL.Path)
		path := r.URL.Path
		pathSplitted := strings.Split(path, "/")
		key := pathSplitted[2]

		// Send the video or image to the data server.
		clientConfig, _ := auth.PrivateKey("root", "id_dsa", ssh.InsecureIgnoreHostKey())
		client := scp.NewClient("10.8.109.3:22", &clientConfig)
		err = client.Connect()
		if err != nil {
			fmt.Println("Couldn't establisch a connection to the remote server ", err)
		}
		defer client.Session.Close()
		remotePath := "/data/" + key
		client.Copy(bytes.NewReader(body), remotePath, "0655", int64(len(body)))

		// And now set a new body, which will simulate the same data we read:
		r.Body = ioutil.NopCloser(bytes.NewBuffer(body))

		return r, nil
	})

**Comment by bramvdbogaerde** [comment]
Commit 1449f3a should have solved the issue.

You will need to use `defer client.Close()` instead of `defer client.Session.Close()`.

@cedricve could you confirm whetever this solved your problem?

**Comment by cedricve** [comment]
cool, i'll try it in the next hours ;) thanks

**Comment by cedricve** [comment]
works like a charm thanks @bramvdbogaerde
